layout_spectrum: 0.727888
typography_spectrum: 0.8686814
color:
  saturation: 0.8609022
  lightness: 0.6611171
  brandStrength: 0.9516284
  brandColors:
    - '#181818'
    - '#FEFFFD'
    - '#29ABB5'
    - '#88928F'
    - '#A3CFC6'
  rhythmicContrast: 0.4381304
name: YouthTrix
